### ISSUE TITLE
Vehicle Routing

### ISSUE THREAD

**Issue by mindymon** [usdigitalresponse/neighbor-express#106] opened 2020-05-06 22:48 UTC
Concord seemingly wanted routing, another city wants to use it (see #project-nex) but I think as-is
From geoff: vehicle routing is kinda on the perennial backlog… it’s like half done but i haven’t gotten it across the line in a way that can actually be demoed for concord with their real data. i suspect it’s only a few hours of work… could float it and see if anyone wants to pick it up. it doesn’t look super likely that i’m going to get to it this coming week

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chompasina** [comment] 2020-05-08 21:20
I'd be curious to learn more about the anticipated technical direction for this. Milwaukee wants it also but they're making do with grouping requests by county for now.

**Comment by neelamsaboo** [comment] 2020-06-29 00:33
This is a duplicate of #149

**Closed as completed by neelamsaboo** 2020-06-29 00:33 UTC
Labels: technical, Priority
